name: fitbasix_chat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  assets_audio_player: ^3.0.6
  cached_network_image: ^3.2.3
  cached_video_player: ^2.0.4
  # cloud_firestore: ^4.8.3
  device_info_plus: ^9.0.2
  dio: ^5.2.1+1
  file_picker: ^5.3.2
  firebase_storage: ^11.2.5
  flutter_cache_manager: ^3.3.1
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  flutter_vibrate: ^1.3.0
  get: ^4.6.5
  google_fonts: ^4.0.4
  image_picker: ^1.0.1
  intl: ^0.18.1
  logger: ^1.4.0
  lottie: ^2.4.0
  mime: ^1.0.4
  open_filex: ^4.3.2
  path_provider: ^2.0.15
  permission_handler: ^10.4.3
  photo_view: ^0.14.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  socket_io_client: ^2.0.2
  url_launcher: ^6.1.12
  uuid: ^3.0.7
  change_app_package_name: ^1.1.0
  # firebase_core: ^2.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
